CREATE TABLE part_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    work_order_id BIGINT NOT NULL,
    part_id BIGINT NOT NULL,

    quantity INTEGER NOT NULL,
    unit_cost DECIMAL(10,2),
    notes VARCHAR(500),

    CONSTRAINT fk_partusage_workorder
        FOREIGN KEY(work_order_id)
        REFERENCES work_order(id),

    CONSTRAINT fk_partusage_part
        FOREIGN KEY(part_id)
        REFERENCES part(id)
);