CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    zip_code VARCHAR(20),
    lat DECIMAL(10, 8),
    lng DECIMAL(11, 8),
    contact_name VARCHAR(150),
    contact_phone VARCHAR(20),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_site_customer
        FOREIGN KEY(customer_id)
        REFERENCES customer(id)
);