CREATE TABLE time_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    work_order_id BIGINT NOT NULL,
    technician_id BIGINT NOT NULL,

    minutes INTEGER NOT NULL DEFAULT 0,
    note TEXT,
    duration INTEGER DEFAULT 0,
    description TEXT,
    start_time TIMESTAMP,
    end_time TIMESTAMP,

    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_timelog_workorder
        FOREIGN KEY(work_order_id)
        REFERENCES work_order(id),

    CONSTRAINT fk_timelog_user
        FOREIGN KEY(technician_id)
        REFERENCES users(id)
);