CREATE TABLE work_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    assigned_to BIGINT,

    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description TEXT,

    priority VARCHAR(30),
    status VARCHAR(30),

    estimated_hours DECIMAL(5,2),
    actual_hours DECIMAL(5,2),
    scheduled_date TIMESTAMP,
    completed_date TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sla_due_at TIMESTAMP,

    CONSTRAINT fk_workorder_customer
        FOREIGN KEY(customer_id)
        REFERENCES customer(id),

    CONSTRAINT fk_workorder_site
        FOREIGN KEY(site_id)
        REFERENCES site(id),

    CONSTRAINT fk_workorder_user
        FOREIGN KEY(assigned_to)
        REFERENCES users(id)
);